version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root   # Set a root password
    ports:
      - "33061:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data-order:/data/db
volumes:
  mysql-data-order: